// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNQ8BpugunQbu6E3H1fSsRtrxCT1ZYS2c',
    appId: '1:213806363722:web:8a4834b003011d56db22b3',
    messagingSenderId: '213806363722',
    projectId: 'medicup-mome',
    authDomain: 'medicup-mome.firebaseapp.com',
    databaseURL: 'https://medicup-mome-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'medicup-mome.appspot.com',
    measurementId: 'G-BR7PVYMX3Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQP7CFJGYGJB1p18UO3UVeGZJQYAJkE9c',
    appId: '1:213806363722:android:1976ad08ccd8e469db22b3',
    messagingSenderId: '213806363722',
    projectId: 'medicup-mome',
    databaseURL: 'https://medicup-mome-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'medicup-mome.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFYl4FGEgOXsCwnEkpAPVOup_N17c_QTE',
    appId: '1:213806363722:ios:9bfd897e9bb42326db22b3',
    messagingSenderId: '213806363722',
    projectId: 'medicup-mome',
    databaseURL: 'https://medicup-mome-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'medicup-mome.appspot.com',
    iosClientId: '213806363722-rff0p2gvtmp4ajroa3kor7n7r2o6kk6p.apps.googleusercontent.com',
    iosBundleId: 'com.example.momentoMedico',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFYl4FGEgOXsCwnEkpAPVOup_N17c_QTE',
    appId: '1:213806363722:ios:9bfd897e9bb42326db22b3',
    messagingSenderId: '213806363722',
    projectId: 'medicup-mome',
    databaseURL: 'https://medicup-mome-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'medicup-mome.appspot.com',
    iosClientId: '213806363722-rff0p2gvtmp4ajroa3kor7n7r2o6kk6p.apps.googleusercontent.com',
    iosBundleId: 'com.example.momentoMedico',
  );
}
